language: python
cache: pip
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install pip --upgrade
  - pip install -e git+https://github.com/XanaduAI/pennylane.git#egg=pennylane
  - pip install -r requirements.txt
  - pip install pytest pytest-cov wheel codecov --upgrade
  - python3 setup.py bdist_wheel
  - pip install dist/PennyLane_IonQ*.whl
script:
  - make coverage
after_success:
  - codecov
=======
requirements_file: doc/requirements.txt

build:
    image: latest

python:
    version: 3.8

# Don't build any extra formats
formats:
    - none
