name: Upload
on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Build and install Plugin
        run: |
          python -m pip install --upgrade pip wheel
          python setup.py bdist_wheel
          pip install dist/PennyLane*.whl

      - name: Install test dependencies
        run: |
          pip install wheel pytest pytest-cov pytest-mock flaky --upgrade

      - name: Run tests
        env:
          IONQ_API_KEY: ${{ secrets.IONQ_API_KEY }}
        run: |
          python -m pytest tests --tb=native
          pl-device-test --device=ionq.simulator --tb=short --skip-ops --shots=10000

      - name: Publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI }}
